site_name: DAT - Database Acceleration Toolkit
docs_dir: "docs"
copyright: "Copyright © Amazon 2023"
site_author: "AWS"
site_url: "https://aws-samples.github.io/aws-database-acceleration-toolkit/"
repo_name: "aws-database-acceleration-toolkit"
repo_url: "https://github.com/aws-samples/aws-database-acceleration-toolkit"
theme:
  logo: images/aws-logo.png
  favicon: images/aws-favicon.png
  name: material
  font:
    text: ember
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs.sticky

  language: en
  palette:
    primary: indigo
    accent: gre
    
nav:
  - Introduction: 'index.md'
  - Getting Started: 'getstarted.md'
  - Deployment:
      - Deployment using CLI: deployment_using_cli.md
      - Deployment using new Jenkins: deployment_using_new_jenkins.md
  - Examples: 'examples.md'
  - FAQs: 'faq.md'
  - Contributors: 'contributors.md'  
  - Get Involved: 'contributing.md'   
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.critic
  - toc:
      permalink: "¤"
  - toc:
      permalink: true
plugins:
  - search
copyright: |
  &copy; Amazon 2023
